### ISSUE TITLE
About the icon SVG file will be updated every time official sync

### ISSUE THREAD

**Issue by MugenLee** [FlorianWoelki/obsidian-icon-folder#146]
**Describe the bug**
I use official synchronization to synchronize data between WIndows10, Android, and iOS devices

I found that every time I sync, I will re-sync the icon pack in the icon folder plugin

So I wonder if the modification time of the svg file of the icon pack is the latest every time, which triggers the official synchronization mechanism

Unfortunately the SVG files I see from my win10 device, indeed all modification times are up to date, but it hasn't been changed for a long time since I configured the icon folder

**To Reproduce**
1. Open any device of windows10, Android, iOS
2. Trigger official synchronization and start synchronizing data
3. It can be seen that every time it is synchronized, the Svg file of the icon pack will be re-synchronized (I only keep one icon pack in the icon folder, so I can recognize it)
4. This icon pack contains 1800+ SVG files, so each synchronization will take a considerable amount of time
5. The crux of the problem is that it has not been changed for a long time after I complete the folder configuration through the icon folder, and I only use 2 icons, so this problem really bothers me.
6. As can be seen from the figure, there are 1820 files, the last modification time was about 20 minutes ago, and all SVG files have this modification time. But the last time I configured the icon folder was half a month ago, and I only used 2 icons

![image](https://user-images.githubusercontent.com/91043731/211450396-6db23dea-ac15-4e38-a7f2-0ffa6c444ef0.png)
![image](https://user-images.githubusercontent.com/91043731/211450723-949996e4-e21f-4525-bc26-a041f253aeea.png)
![3a94eae590e520038d97a1286512525](https://user-images.githubusercontent.com/91043731/211451051-e38760a2-fcbd-4a0e-b943-8f4921e39289.jpg)

**Expected behavior**
1. I hope that every time I synchronize, I don’t want to synchronize 1820 SVG files all over again

2. Unless the icon foder updates the configuration, it does not need to be synchronized

Hope to solve this problem soon

If you need any support from me, please feel free to contact me
@FlorianWoelki 

looking forward to reply~

**Comment by bjornkemps** [comment]
I have the same issue, might be because I sync between a Windows and OSX host and file compare has difficulties.
Workaround:
Add exclude from sync entry: .obsidian/plugins/obsidian-icon-folder/icons, and repair the Icon Packs afterwards.

**Comment by MugenLee** [comment]
> I have the same issue, might be because I sync between a Windows and OSX host and file compare has difficulties. Workaround: Add exclude from sync entry: .obsidian/plugins/obsidian-icon-folder/icons, and repair the Icon Packs afterwards.

Thanks for the answer~

Does shielding need to be set on all terminals used?

For example, if I use window10+Android+iOS, then I only need to set up the PC, or do I need to set up the PC+two mobile phones?

**Comment by bjornkemps** [comment]
> > I have the same issue, might be because I sync between a Windows and OSX host and file compare has difficulties. Workaround: Add exclude from sync entry: .obsidian/plugins/obsidian-icon-folder/icons, and repair the Icon Packs afterwards.
> 
> Thanks for the answer~
> 
> Does shielding need to be set on all terminals used?
> 
> For example, if I use window10+Android+iOS, then I only need to set up the PC, or do I need to set up the PC+two mobile phones?

It seems like you've to setup this exclution manually, once on each device you use Sync with and then repair the Icon Packs as well on each device to be sure the Icons are working correctly.

**Comment by MugenLee** [comment]
> > > I have the same issue, might be because I sync between a Windows and OSX host and file compare has difficulties. Workaround: Add exclude from sync entry: .obsidian/plugins/obsidian-icon-folder/icons, and repair the Icon Packs afterwards.
> > 
> > 
> > Thanks for the answer~
> > Does shielding need to be set on all terminals used?
> > For example, if I use window10+Android+iOS, then I only need to set up the PC, or do I need to set up the PC+two mobile phones?
> 
> It seems like you've to setup this exclution manually, once on each device you use Sync with and then repair the Icon Packs as well on each device to be sure the Icons are working correctly.

OK , I try it. thanks~

**Comment by thomasvochten** [comment]
Silly question maybe, but how do I exclude the icons folder from sync? I don't seem to be able to exclude anything from my .obsidian folders - but maybe I'm holding it wrong :-)

**Comment by thomasvochten** [comment]
> > Silly question maybe, but how do I exclude the icons folder from sync? I don't seem to be able to exclude anything from my .obsidian folders. Putting the path in and clicking "Done" doesn't work for this folder - but maybe I'm holding it wrong :-)
> > ![image](https://user-images.githubusercontent.com/135686/213415319-467f9a73-e5dd-4df3-ba49-846770e35cc9.png)
> 
> Press enter after typing the path.

wow - thanks! I *do* feel silly now :-)

**Comment by FlorianWoelki** [comment]
This is an official syncing issue and a possible solution might exist in #153.
The issue will be probably solved in `v2.0.0` (#159)

Closing this issue for now.

**Comment by MugenLee** [comment]
Reply to this question. First of all, I am very grateful to the author for his hard work. I have been using this plugin and I have always liked it, but unfortunately this problem still exists, even if I update to v2.0.1

Let me introduce my solution below, and the effect is satisfactory：

Deleted the original icon pack, created a new custom icon pack folder, and added the required icon SVG files into it

After that, even if the plug-in is synchronized all the time, it only synchronizes these two files, which reduces the number and pressure of synchronization. It is an indirect solution.
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/91043731/121f863b-21f7-4c1b-ab4c-e1692af4efaf)
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/91043731/089bd48d-7f3b-4bf5-8b02-3988daba5ef7)
