### ISSUE TITLE
Doubled inherited icons of items inside a folder

### ISSUE THREAD

**Issue by SaifEl-Deen** [FlorianWoelki/obsidian-icon-folder#216]
**Describe the bug**
Doubled inherited icons of items inside a folder

**To Reproduce**
1. Create a folder
2. Create notes inside that folder
3. Set an icon for the folder
4. Inherit this icon to the notes
5. Change the icon of the folder
6. Inherited icons of the notes aren't updated + "Inherit" option becomes available again
7. Inherit icons again, you will get double icons

NOTE: I'm not able to reproduce it although I'm 100% sure that's how it happened

**Expected behavior**
To update the inherited icon when the parent folder icon is updated
To remove the inherited icon when the parent folder icon is removed

**Screenshots**

**Additional context**

**Comment by swfvanrijk** [comment]
Also happened to me. Set the icon of a subfolder, than set the inherit icon of the higher folder. I am not able to remove all the icons after it happened:
![afbeelding](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/35876323/7e4e9c51-5e31-4ba9-bf2c-a0ccb329831a)

**Comment by funamorisenji** [comment]
I also have the same issue, help fix it.

**Comment by FlorianWoelki** [comment]
Could you please provide some extra detailed steps on how I can reproduce this? Because at the moment I cannot reproduce this issue.

**Comment by funamorisenji** [comment]
I do following this: 
1. Create a folder/note inside the folder that already set the `Inherit Icon` 
2. After you create, reload the window again by using `cmd+P`.
3. After the Obsidian window re-open, you will see the icon is duplicate in the folder that inside the `Inherit Icon` folder

![CleanShot 2023-09-10 at 00 44 43@2x](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/38547838/13738d13-2f1a-4b9e-9acf-a763f677b8c1)

**Comment by FlorianWoelki** [comment]
This should be fixed in [2.2.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.2.0)

**Comment by funamorisenji** [comment]
@FlorianWoelki  Thanks for the update but after I update to version 2.2.1 still have the duplicate problem as the video here. 

https://github.com/FlorianWoelki/obsidian-icon-folder/assets/38547838/76d86473-76eb-4226-90cc-24ae87fad81a

**Comment by FlorianWoelki** [comment]
I've pushed another fix. This will be probably released within the next days.

In theory, directories are not supported anymore to have inherited icons. There was a smaller issue with renaming/creating directories.

**Comment by funamorisenji** [comment]
@FlorianWoelki 
Thanks man, looking forward to it. Cheer!

**Comment by funamorisenji** [comment]
@FlorianWoelki 
Is another fix have been publish and ready for update on Obsidian?

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki Is another fix have been publish and ready for update on Obsidian?

Nope, it will be released within this week.
