### ISSUE TITLE
Search Issues when Icon Folder Plug-in is enabled

### ISSUE THREAD

**Issue by AndEliRich** [FlorianWoelki/obsidian-icon-folder#74]
When this Icon Folder plug-in is enabled on iOS (using Obsidian insider build v. 1.2.2), search functionality does not work. It either causes the search functionality to be excessively slow or (more frequently) causes the app to crash. I disabled all plug-ins and themes and was able to narrow down the issue to this particular plug-in. This was the ONLY plug-in that, when enabled, caused issues with search on the mobile app. I have not had the same issues on the desktop app. 

My mobile app is running on an iPhone 13 pro max, running the latest iOS version (15.5). 

When this plug-in is enabled, trying to use search on Obsidian causes the entire app to crash OR is exceedingly slow OR won't allow me to open documents that are returned in the search (most often trying to open them just causes the entire app to crash).

**Comment by FlorianWoelki** [comment]
Is it fixed with the newest version `1.2.3`?

**Comment by FlorianWoelki** [comment]
Issue closed because of inactivity.

**Comment by 411A** [comment]
Unfortunately encountered the same issue, it still persists! On Windows 10, global search is not working at all when this plugin is enabled! it shows nothing. it seems that the plugin has some incompatibility with the search layout.

**Comment by FlorianWoelki** [comment]
> Unfortunately encountered the same issue, it still persists! On Windows 10, global search is not working at all when this plugin is enabled! it shows nothing. it seems that the plugin has some incompatibility with the search layout.

I cannot reproduce this anymore with the newest version.
