### ISSUE TITLE
Inconsistent sets of icons between mobile and desktop

### ISSUE THREAD

**Issue by huyz** [FlorianWoelki/obsidian-icon-folder#81]
There are so many weird things going on that I don't know where to begin.

In general, it's impossible for me to get all icons working both in mobile and on desktop. Either I set them all on one side, sync, and then the other side will miss some icons; or I do the same on the other side, sync, and the former side will miss some icons.

I get things like this all the time, either on mobile or on desktop:
![screenshot 2022-06-18T113757Z](https://user-images.githubusercontent.com/128394/174435803-bb91cbc1-da17-4648-9b02-e60eb55d1fb4.png)

I set the icons folder to `~/.obsidian/icons` and that didn't solve any problem.
Deleting icon packs and re-downloading them doesn't solve the problems because it seems that you never get 100% of the same icons each time. Some icons are missing here and there.

And it's hard for me to diagnose because I don't understand where icon search results come from.  For example, right now if I search "for server", I get:
![screenshot 2022-06-18T113354Z](https://user-images.githubusercontent.com/128394/174435685-36414c1a-8505-4011-aa32-ce5f1843c99b.png)

But if look on my macOS filesystem, I can only find ServerFill. Where does ServerLine come from?
```
❯ ls */*Server*
remix-icons/ServerFill.svg
```

**Comment by huyz** [comment]
And when I delete icon packs and re-download them, some of the existing folder icons get refreshed, some don't, even after restarting Obsidian.
So I have to go through each folder and re-select the same icon for it to be refreshed.

**Comment by FlorianWoelki** [comment]
Sorry to hear about this issue.

I cannot really reproduce it without having some small reproduction vault.
However, you could try to download the icon pack for yourself and extract it into the icons folder. Maybe that will solve some problems.
I could also imagine that your syncing service is syncing things wrong.

**Comment by huyz** [comment]
I did as you suggested and manually downloaded the icons.  After normalizing the filenames as your plugin does, here are all the SVGs that were missing:

![screenshot 2022-06-21T094502Z](https://user-images.githubusercontent.com/128394/174770459-d27c3db4-2c88-4ba7-9a4f-9a04df38b2a8.png)

Now these are exactly the icons that were missing (at least for this icon pack) and which I've manually selected in the past to assign to folders.  This implies that there isn't fault in the downloading process, and there's a bug that that actually deletes icons—indeed delete some of the very icons that I need.

**Comment by huyz** [comment]
This is the problem: https://github.com/FlorianWoelki/obsidian-icon-folder/blob/main/src/iconPackBrowserModal.ts#L64

![screenshot 2022-06-21T102307Z](https://user-images.githubusercontent.com/128394/174777810-702d5627-650d-4f92-ae1b-ab9cfb442cb4.png)


Hopefully, this is the only problem

**Comment by FlorianWoelki** [comment]
Could you please provide me with the icon pack name? Maybe I can reproduce this.

**Comment by huyz** [comment]
This applies to any of the 4 icon packs. To reproduce this:
1. download one of the icon packs
2. Set icon folder on several folders
3. Maybe restart Obsidian
4. delete icon pack
5. Maybe restart Obsidian
6. Open Dev console
7. reinstall the icon pack
8. look for errors in the console
9. look in the filesystem and see that all the icons that you had chosen in step #2 are missing

**Comment by huyz** [comment]
I looked at the DOM in the File Explorer to see what the line `this.plugin.app.workspace.containerEl.querySelector(`[data-path="${path}"]`);` is trying to get to.
And I can see that the DOM for my folders is incomplete: it doesn't include my folders that aren't in view.  If I scroll down the File Explorer and the folders come into view, then the DOM changes as elements for visible folder icons are added and the elements for invisible folder icons are removed.
But until then, since `[data-path="My folder that is not in view"]` will naturally return null.

**Comment by FlorianWoelki** [comment]
I cannot really reproduce this. What exactly do you mean by invisible folders?
In addition, could you provide me with an example for reproduction?

**Comment by huyz** [comment]
Invisible folders means you have such a long list of folders that the list overflows in the File Explorer.  I just mean "out of view".  
Instead of rendering the entire list of folders in the File Explorer, it seems that OBsidian optimizes by incrementally adding to the DOM folders that come into view and removing from the DOM folders that go out of view as you scroll.

**Comment by huyz** [comment]
My guess as to the reason why you can't reproduce is that your File Explore pane is quite tall, which isnt' the case for me.  For effect, I've shrunk mine further to show you:
![screenshot 2022-07-02T090801Z](https://user-images.githubusercontent.com/128394/176994197-5339c1a2-1876-4f45-b26b-20f36340515a.png)


As you can see there are lots of folders below `_templates` that are not in view

**Comment by FlorianWoelki** [comment]
Ok got it! This should be fixed whenever a new version is released. I've fixed it yesterday.

**Comment by huyz** [comment]
Awesome. Thank you so much!

**Comment by RustedAperture** [comment]
![image](https://user-images.githubusercontent.com/6724171/183265335-a816ef57-e61a-4b32-8e98-2d42947264ed.png)

Still happening when using custom icon packs. I have the exact same files on both my mobile and desktop... its still not showing properly.

I copied the folders from my desktop to my phone and put them in the same place.

**Comment by huyz** [comment]
Yeah it seems that a few icons are still missing on mobile. It's not as bad as before though. And doesn't seem as consistent. I assume mobile DOM acts a bit different than on desktop

**Comment by huyz** [comment]
Yeah this is a very similar problem on mobile: when folders are in view, then these icons will be installed, but any folders not in view (i.e., not in the DOM) at the moment will not have the icons installed.
