### ISSUE TITLE
What to do with this notice?

### ISSUE THREAD

**Issue by mohitmujawdiya** [FlorianWoelki/obsidian-icon-folder#84]
Hi! First off, thanks for creating such a great plugin.

I am getting this notice whenever I start obsidian. I went to .obsidian/plugins/ and the is the plugin folder named "obsidian-icon-folder". Is it asking me to move that folder? To where?

![image](https://user-images.githubusercontent.com/61835205/174537546-795d3eb8-61e4-4133-875f-1482e11ec883.png)

**Comment by FlorianWoelki** [comment]
Thanks. This Notice can be a bit misleading I agree. That's why I will change the text of it in v1.2.5.

To fix that: go to settings and change the icon pack folder path to `./obsidian/<your path`. I hope this resolves this issue.

**Comment by mohitmujawdiya** [comment]
Hi, Thank you so much for such a quick reply. It's fixed now!

**Comment by Liong1976** [comment]
I have changed the icon folder pack to `./obsidian/plugins/obsidian-icon-folder/icons`, but the notification still appears. What should I do? Thanks

**Comment by mohitmujawdiya** [comment]
Remove / after the period

**Comment by Liong1976** [comment]
It didn't work. It said, The directory already exists

**Comment by mohitmujawdiya** [comment]
If you're not using the plugin very extensively, you can remove and install it again.

**Comment by Signynt** [comment]
I can not set the folder to be `.obsidian/icons` anymore via the settings, it tries to save it, but never actually does. It seems the period is the issue.
I can edit the `data.json` file directly to say `.obsidian/icons`, and then it works correctly.
